apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bonus-proj
  labels:
    app: bonus-proj
spec:
  description: Our ArgoCD Project for the IOT project
  sourceRepos:
  - "http://192.168.42.110:8080/root/*"
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
