# This is CentOS 9 stream (it is apparently the new maintened lineup of versions)
BOX = "generic/centos9s"

MEMORY = 2048
CPUS = 4

SERVER_IP = "192.168.42.110"
SERVER_HOSTNAME = "gboucettS"

WORKER_IP = "192.168.42.111"
WORKER_HOSTNAME = "gboucettSW"

NET_NAME = "vboxnet0"

Vagrant.configure("2") do |config|
	# Common config for all VM
	config.vm.box = BOX

	config.vm.provider "virtualbox" do |vb|
		vb.memory = MEMORY
		vb.cpus = CPUS
	end

	# Defining all VM

	config.vm.define "server" do |server|
		server.vm.network "private_network", ip: SERVER_IP
		server.vm.hostname = SERVER_HOSTNAME

		server.vm.provider "virtualbox" do |vb|
			vb.name = SERVER_HOSTNAME
		end
	end

	config.vm.define "worker" do |worker|
		worker.vm.network "private_network", ip: WORKER_IP
		worker.vm.hostname = WORKER_HOSTNAME

		worker.vm.provider "virtualbox" do |vb|
			vb.name = WORKER_HOSTNAME
		end
	end
end
