# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "bento/ubuntu-22.04"

MEMORY = 8192
CPUS = 8
HOSTNAME = "gitlab"

IP = "192.168.42.110"

Vagrant.configure("2") do |config|
	config.vm.box = BOX

	config.vm.provider "virtualbox" do |vb|
		vb.name = HOSTNAME
		vb.cpus = CPUS
		vb.memory = MEMORY
	end

	config.vm.network "private_network", ip: IP

	config.vm.provision "shell", path: "scripts/install.sh", name: "Install all requirements"
	config.vm.provision "shell", path: "scripts/setup.sh", name: "Launching all services"
	config.vm.synced_folder "conf/", "/srv/k3d/conf"

	config.vm.provision "shell", run: "never" do |sh|
		sh.name = "gitlab-pwd"
		sh.privileged = false
		sh.inline = <<-SHELL
		kubectl exec -n gitlab $(kubectl get pods -n gitlab -o name) -- cat /etc/gitlab/initial_root_password
		SHELL
	end
end
