# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "bento/ubuntu-22.04"

MEMORY = 4096
CPUS = 4
HOSTNAME = "gitlab"

IP = "192.168.42.110"

Vagrant.configure("2") do |config|
	config.vm.box = BOX

	config.vm.provider "virtualbox" do |vb|
		vb.name = HOSTNAME
		vb.cpus = CPUS
		vb.memory = MEMORY
	end

	config.vm.network "private_network", ip: IP

	config.vm.provision "shell", path: "scripts/install.sh", name: "Install all requirements"
	config.vm.provision "shell", path: "scripts/setup.sh", name: "Launching all services"
	config.vm.synced_folder "conf/", "/srv/k3d/conf"

	# TODO: add the following line to provision
	# export KUBECONFIG=$(k3d kubeconfig merge cluster-gitlab --kubeconfig-switch-context)
end
