apiVersion: apps/v1

kind: Deployment
metadata:
  name: gitlab-deployment
spec:
  replicas: 1

  selector:
    matchLabels:
      app: gitlab-pod

  template:
    metadata:
      labels:
        app: gitlab-pod

    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        env:
        - name: GITLAB_OMIBUS_CONFIG
          value: "external_url 'http://192.168.42.110:8080/'; gitlab_rails['initial_root_password'] = 'password';"

        ports:
        - name: http
          containerPort: 80

---

apiVersion: v1

kind: Service
metadata:
  name: gitlab-service
spec:
  selector:
    app: gitlab-pod
  ports:
  - name: http
    port: 80
    protocol: TCP

# tMJI+iX4sXTbGLLT7aMEZB2BgiHr5uWk/bgPR63VZyc=
